def init():
	global DEVICE_RESID
	global SCENE_NAME
	global LATEST_SCREENSHOT_PATH
	global SNAP_COUNT
	global FIX_ROTATION_NEEDED
	global GAME_OBJECT
	global DEVICE
	global FOUND_BOSS_AND_FIGHTING
	DEVICE_RESID = ""
	SCENE_NAME = ""
	LATEST_SCREENSHOT_PATH = "./"
	SNAP_COUNT = 0
	FIX_ROTATION_NEEDED = False
	GAME_OBJECT = None
	DEVICE = None
	FOUND_BOSS_AND_FIGHTING = False
